### ISSUE TITLE
Update for RCP core radio fields

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-braintree#9]
In https://github.com/restrictcontentpro/restrict-content-pro/issues/658 we're moving away from the dropdown to radio buttons. With this change, when another gateway is selected (like Manual), the Braintree billing fields still show.

**Comment by pippinsplugins** [comment]
@mindctrl could we get this updated this week to work with both select and radio fields to help prevent issues with 2.7 when released?

**Comment by mindctrl** [comment]
@pippinsplugins PR submitted.

**Comment by pippinsplugins** [comment]
PR looks good. Deploy at will.
